version: '3.7'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: attendance
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    image: attendance
    restart: always
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: attendance
    ports:
      - 8888:80
    depends_on:
      - db
volumes:
  dbdata:
